# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd with a custom reset command
# OPENOCD_CMD_RESET_RUN =-c _reset
include $(RIOTMAKE)/tools/icoprog.inc.mk
